### ISSUE TITLE
nqp files are not recognized

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/perl6-mode#10]
I think perl6-mode should be used for nqp files as well.

**Comment by tbrowder** [comment]
On Sat, Feb 4, 2017 at 12:31 Aleks-Daniel Jakimenko-Aleksejev <
notifications@github.com> wrote:

> I think perl6-mode should be used for nqp files as well.
>

I agree, and my setup does. I'll check to make sure the master branch has
that capability.

**Comment by AlexDaniel** [comment]
Hm, actually I'm not sure which version I am using.

**Comment by AlexDaniel** [comment]
According to [this commit](https://github.com/perl6/perl6-mode/commit/4b012444900aeaed0c5c1633869f71ba28546e9f) it should work. I think it is a problem on my end.

**Comment by tbrowder** [comment]
On Tue, Feb 7, 2017 at 12:26 Aleks-Daniel Jakimenko-Aleksejev <
notifications@github.com> wrote:

> According to this commit
> <https://github.com/perl6/perl6-mode/commit/4b012444900aeaed0c5c1633869f71ba28546e9f>
> it should work. I think it is a problem on my end.
>

Let me check my system--it may not be your problem.
