### ISSUE TITLE
Tasklist: break fork and assume MELPA package ownership

### ISSUE THREAD

**Issue by treyharris** [perl6/perl6-mode#11]
The original mode from which this has been forked seems to have been abandoned. This is problematic, because updates are not being reflected in MELPA, from where most Emacs users get packages.

This is unsustainable as it could eventually block adoption of Perl 6 by Emacs users. It also seems like the [Perl 6 GitHub project](/perl6) is the right place to be the focus of development for the Emacs mode, since it's historically been one of the most popular editors for Perl programmers.

This is a punch list for what's required to get this repo to be the "official" one:

- [x] Make one more attempt to contact @hinrik by dropping an issue in the [upstream's issues](/hinrik/perl6-mode/issues) pointing at this issue
- [x] Wait 1 week for a response
- [ ] Snapshot the [network graph](/hinrik/perl6-mode/network), since we need to inform contributors to any other forks once this has been completed
- [x] Ask an Owner of the Perl 6 project to open a support issue with GitHub asking them to break the fork, so that this repo becomes a canonical one (this is required for MELPA to accept this repo as the new canonical source) — **being tracked in #12**
- [x] Verify support issue has been opened
- [x] Wait for GitHub support to break the fork
- [ ] Edit the [perl6-mode recipe](/melpa/melpa/blob/master/recipes/perl6-mode) to point here and submit a pull request (linked back here)
- [ ] Verify the package is on MELPA
- [ ] Inform any previous forks identified in the prior step
- [ ] Go through the old [upstream's issues](/hinrik/perl6-mode/issues) and see if any still apply; if so, open them here as new issues and reference them in the old

I'd like to hear comments on this plan. I'm comfortable taking care of all the steps, and will also create projects and milestones in this project.

I will begin with contacting @hinrik—since this is a necessary step regardless of the plan—seeking his response by 1 week from now, Sun 14 May 2007.

**Comment by JJ** [comment]
Thanks, and good luck.

**Comment by treyharris** [comment]
I have notified @hinrik in hinrik/perl6-mode#20.

**Comment by hinrik** [comment]
:+1:

**Comment by AlexDaniel** [comment]
Update? @hinrik seemed to agree to transfer it, so maybe we should simply ask him to do it (and move this current repo to ``perl6-mode-fork``). This way github will automatically install the redirect, so everything else will be significantly easier.

**Comment by zakame** [comment]
Hello, thanks everyone for making this happen and to @hinrik too for the fine mode!

For the meanwhile, a way for using this fork while waiting for update to MELPA might be via [quelpa][0] and use-package, e.g.

[0]: https://github.com/quelpa/quelpa

```
(use-package perl6-mode
  :quelpa (perl6-mode :fetcher github :repo "perl6/perl6-mode"))
```

Another way might be for the Perl 6 community to run its own Emacs package archive, maybe on p6c.org, as a future location for Perl 6 Emacs packages beyond major-mode (such as autocompletion or IDE functionality) akin to [elpy][1].

[1]: https://github.com/jorgenschaefer/elpy

**Comment by kaicarver** [comment]
Hi @treyharris any news on this? 

I was happy to (laboriously) figure out how to install `perl6-mode` from these instructions:
http://linuxtot.com/perl6-major-mode-for-emacs-how-to-install/
but I gather that's still the old version. How do I update to the latest version hosted here? I tried @zakame 's method but it didn't work ("Unrecognized word: :quelpa")

Sorry I am a long-time Emacs user but not terribly well-versed in `.emacs` files and such. Shameful, I know, but I imagine I am not the only one.

I guess I could search around in my directory and replace files with the files hosted here... Not sure if it's worth it and hoping there's a better way. Let me know if there's anything I can do to help.

**Comment by zakame** [comment]
@kaicarver if you're using my method, you'll need to set up [use-package](https://github.com/jwiegley/use-package) and [quelpa](https://github.com/quelpa/quelpa-use-package) first if you want to use it.  In brief (taken from my [.emacs.d](https://github.com/zakame/.emacs.d), assumes you already have use-package installed:)

```emacs-lisp

(use-package quelpa-use-package
  :ensure t
  :config
  (setq quelpa-update-melpa-p nil))

(use-package perl6-mode
  :quelpa (perl6-mode :fetcher github :repo "perl6/perl6-mode"))
```

**Comment by kaicarver** [comment]
@zakame looks like that worked! Thanks for your help.

**Comment by zakame** [comment]
@kaicarver happy to help!

I suppose for this issue now, we're being blocked by #12 , perhaps we could ping there?

**Comment by zakame** [comment]
This repo is no longer a fork, thanks @moritz !

![image](https://user-images.githubusercontent.com/110625/30049288-9cf18f9c-924c-11e7-9f48-c226ba143d76.png)

**Comment by zakame** [comment]
Here are the current dependents of @hinrik's perl6-mode, via https://github.com/hinrik/perl6-mode/network/members:

![image](https://user-images.githubusercontent.com/110625/30049342-dc02c804-924c-11e7-8da9-6420167f387a.png)

I can go over to them and notify about this repo now being the new canonical repo.

**Comment by JJ** [comment]
Consider me notified :-)

**Comment by tbrowder** [comment]
On Tue, Sep 5, 2017 at 07:18 Juan Julián Merelo Guervós <
notifications@github.com> wrote:

> Consider me notified :-)


ditto!

**Comment by treyharris** [comment]
Thank you! Can we close this out now?

**Comment by zakame** [comment]
I suppose we can wait first on MELPA to update, then close this once we confirm the new package is on the repo.
