### ISSUE TITLE
Work with treyharris on GitHub support ticket to unfork the perl6-mode repo

### ISSUE THREAD

**Issue by treyharris** [perl6/perl6-mode#12]
@perl6/org-admins: I put a call out on IRC #perl6 but since that won't get everyone, I'll repeat my request here:
> ...It seems ilke the canonical Emacs perl6-mode has been abandoned (9 months of author inattentiveness), but the fork under the perl6/ GitHub project can't be made official for Emacs packaging because it's a fork. I've made a tasklist on GitHub (#11) to track this, and right now we're still in step [no. 2](https://github.com/perl6/perl6-mode/issues/11#issue-226884715)—wait a week to see if the original author returns after informing him of our intentions to take over maintenance—but assuming he doesn't respond or blesses the transfer, we'll need an [Owner of the GitHub Perl 6 project](https://github.com/orgs/perl6/people?utf8=%E2%9C%93&query=%20role%3Aowner) to handle working with GitHub support to break the fork and move over the open issues. (This is something they do, but only in a support-ticket context, there's no interface or API for it.)

I'd take care of it—I've done this before in other projects on GitHub—but I'm not an Owner so can't. Would one of you be willing to help me with this next week (that is, the week beginning Sunday 14 May)?

Again, since I've done this before, I can lead you through it. I just don't have the access rights to do it here. If you can volunteer, please reply and/or assign yourself this issue.

Thanks!

**Comment by tbrowder** [comment]
I can help after I get back to US on 15 May

**Comment by treyharris** [comment]
@tbrowder Thanks for the offer to assist. But I think perhaps you meant to offer assistance in #11 rather than here? We need a [github.com/perl6 project Owner as listed in this link](https://github.com/orgs/perl6/people?utf8=%E2%9C%93&query=%20role%3Aowner) to work with me to handle this particular task. The other tasks in the umbrella list in #11 has tasks that could be offloaded (though I'm happy to take care of all of them).

**Comment by zakame** [comment]
Hi @perl6/org-admins, asking your attention for this issue once more. :smile_cat:

**Comment by moritz** [comment]
I've contacted GitHub support about this issue.

**Comment by moritz** [comment]
They've done their magic.

**Comment by zakame** [comment]
Thanks @moritz ! :tada:
